// src/app/journal/auto/page.js
import { PRIMARY_USER_ID } from "@/lib/constants";
import { getRecentMemories } from "@/lib/supabase";

export const dynamic = "force-dynamic";

export default async function AutoJournalPage() {
  const userId = PRIMARY_USER_ID;

  // Grab recent memories and filter in code to type = "journal"
  const recent = await getRecentMemories({
    userId,
    limit: 100,
    minImportance: 1,
  });

  const journalEntries = (recent || []).filter(
    (m) => m.type === "journal"
  );

  return (
    <div className="min-h-screen flex items-center justify-center px-2 py-4 sm:px-4">
      <div className="w-full max-w-4xl space-y-5">
        {/* Header */}
        <header className="flex flex-col justify-between gap-3 rounded-2xl border border-slate-800/80 bg-slate-950/70 px-4 py-3 shadow-lg shadow-black/40 backdrop-blur sm:flex-row sm:items-center sm:px-6">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-500/15 ring-2 ring-emerald-500/60">
              <span className="text-xl">🧠</span>
            </div>
            <div>
              <h1 className="text-base font-semibold text-slate-50 sm:text-lg">
                Auto Daily Journal
              </h1>
              <p className="text-xs text-slate-400 sm:text-sm">
                These entries are auto-generated by Jarvis from your
                conversations and check-ins, stored in Supabase
                (<code className="text-[0.65rem]">jarvis_memory</code>,{" "}
                <code className="text-[0.65rem]">type = &quot;journal&quot;</code>).
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2 text-xs sm:text-[0.7rem]">
            <a
              href="/journal"
              className="rounded-full bg-slate-900/80 px-3 py-1 text-slate-300 ring-1 ring-slate-700 hover:bg-slate-900"
            >
              ← Manual trade journal
            </a>
            <a
              href="/"
              className="rounded-full bg-emerald-500/15 px-3 py-1 font-medium text-emerald-200 ring-1 ring-emerald-500/60 hover:bg-emerald-500/25 transition"
            >
              Back to Jarvis chat
            </a>
          </div>
        </header>

        {/* Body */}
        <main className="space-y-4">
          {journalEntries.length === 0 ? (
            <div className="rounded-2xl border border-slate-800/80 bg-slate-950/80 p-5 text-sm text-slate-400 shadow-xl shadow-black/40 backdrop-blur">
              No auto-journal entries yet.
              <br />
              Once the daily cron runs and you&apos;ve had some
              conversations / check-ins, Jarvis will start writing a daily
              summary here.
            </div>
          ) : (
            <div className="space-y-4">
              {journalEntries.map((entry) => {
                const created = new Date(entry.created_at);
                const firstLine =
                  entry.content.split("\n").find((l) => l.trim()) ||
                  entry.content.slice(0, 120);

                return (
                  <article
                    key={entry.id}
                    className="rounded-2xl border border-slate-800 bg-slate-950/80 p-4 shadow-xl shadow-black/40 backdrop-blur space-y-2"
                  >
                    <div className="flex items-center justify-between text-[0.7rem] text-slate-400">
                      <span>
                        {created.toLocaleDateString()} •{" "}
                        {created.toLocaleTimeString()}
                      </span>
                      <span className="rounded-full border border-emerald-500/60 bg-emerald-500/10 px-2 py-0.5 text-[0.65rem] font-semibold text-emerald-300">
                        AUTO JOURNAL
                      </span>
                    </div>

                    <p className="text-sm font-medium text-slate-100">
                      {firstLine}
                    </p>

                    <details className="mt-1 text-xs text-slate-300">
                      <summary className="cursor-pointer text-emerald-300">
                        Show full entry
                      </summary>
                      <div className="mt-2 whitespace-pre-wrap">
                        {entry.content}
                      </div>
                    </details>
                  </article>
                );
              })}
            </div>
          )}
        </main>
      </div>
    </div>
  );
}
